language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.8
services:
- docker
- postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
env:
  global:
  - PG_USER=postgres
  - PG_PASSWORD=""
  - PG_DBNAME="jdbc:postgresql://127.0.0.1/smartportal_dev"
before_script:
- export DEBIAN_FRONTEND=noninteractive;
  sudo -E apt-get -yq update &>> ~/apt-get-update.log;
  sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.3
- psql -c 'create database smartportal_dev;' -U postgres
- psql -U postgres -c "create extension postgis"
script:
- sbt compile coverage test scapegoat check coverageReport copyCoverage makeSite
before_install:
- openssl aes-256-cbc -K $encrypted_bfe1df66c3c1_key -iv $encrypted_bfe1df66c3c1_iv
  -in ghpages_ecdsa_sacback.enc -out ghpages_ecdsa_sacback -d
after_success:
- chmod 600 ghpages_ecdsa_sacback && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacback
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ghpagesPushSite
- sbt clean universal:packageZipTarball
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && pwd && sh -c $TRAVIS_BUILD_DIR/docker-preps.sh
deploy:
  provider: gcs
  access_key_id: GOOGZDYY4PCU7QXHJ5GS
  secret_access_key:
    secure: fV66wuLV0xGPraRLP/5tznljq670nS6vqW0dBWK98DDtURW7+Kr8+4wTTD+Xq8oI1YW1TZ3V27jIqMs+yusi6/s0BX5BDSbQtXWmUbLXgZF2jb5fSCnG8sXEJodvsuoBoqXJgUoBqt6m0MB9Ro+gU7/YuH9Pz23hmiI6kbYlqcuRogQYhfpx1u1ik/2RRB8YIAgV4T9KQ3dLy7JK4DQ3rPtUYX5JOR9eSPTF+D/7o0+3aj3PMx+8bMPmXKarn/3fdPTQknWFaaeKm4NdcyJS+Bf5KQ3VXVzJkIRolw2U7KOZ8kXTPXYhHuFi9Eu4AkBVABY1FNvi8zibJ158YgYdMiihYXCyVl3EMTGgFLXNFDBnIc4X4JDdp+RKMC0yrirSgv08yaWvH0bGNGTH0P5o/F8rVrfXWhbymDIoBnVtUN0oc+RnH5XizwJngh6iVnI4vt53Thhj1M6txUU95c1jymg4znkKTbXuWaiQw74pvqBC5VypAb/tes2vIEM/Nl7WQN8LjGy+eYTO7n96iBOn0APNh9xLstuhaBjlc0txmq63GmYSKYvzxZafyfphhHBu126ss67JjYhQkTgg7uNGFxGYHkM4csXImQCzi+WhJFTQj1C2Ip5SkevpXEO+mmOUEn418Tvn7pLUwmYiIlR6pTPZ5EwM+siGEjZozHKaoMg=
  bucket: smart-deploy-artefacts
  upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER"
  local-dir: target/universal/
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
  - allixender@googlemail.com
  webhooks:
    urls:
    - https://admin.smart-project.info/travis/notification
    on_success: always
    on_failure: never
    on_start: never
