language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.8
services:
- docker
- postgresql
addons:
  postgresql: "9.4"
env:
  global:
  - PG_USER=postgres
  - PG_PASSWORD=""
  - PG_DBNAME="jdbc:postgresql://127.0.0.1/smartportal_dev"
before_script:
- psql -c 'create database smartportal_dev;' -U postgres
- psql -U postgres -c "create extension postgis"
script:
- sbt compile coverage test scapegoat check coverageReport copyCoverage makeSite universal:packageZipTarball
before_install:
- openssl aes-256-cbc -K $encrypted_bfe1df66c3c1_key -iv $encrypted_bfe1df66c3c1_iv
  -in ghpages_ecdsa_sacback.enc -out ghpages_ecdsa_sacback -d
after_success:
- chmod 600 ghpages_ecdsa_sacback && eval `ssh-agent -s` && ssh-add ghpages_ecdsa_sacback
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ghpagesPushSite
deploy:
  provider: gcs
  access_key_id: GOOGZDYY4PCU7QXHJ5GS
  secret_access_key:
    secure: qy+lm6XDtOkE7AQbRR0DpI8zlBH9Ge//OFJSPHgRsfs9Ro1Baupkt977NiiyK36mCP27dAbtoHGBQsByzSa96us1Vtd/iKyXofNWcNXZDf1U1gxj0Kg4wpb4CbERp/Sh/yqoqDI81oSfWVtTVSm4DXrWWiXX2+O7Zs53rXOCMkq8JKQesDu5icz05Y1sg5gxIIqR85K2J1tnaamKqkm63Wcm4WCmxdAKWP8Gj1v5CnRDI7syhhBOF+3CB/sh3mgxPNWlQEj0GAAY8OLvU4/Ofx1vczeNO0c2PHqIAjqTpkN5om1lxr37FuyC827NuQZvYVBj8O9+ZZ3nr/Nc5+X9VVu/CPu8y5lReU/Oc6g9Wmjkp5+JacryxUDiokDob6DmIg0q6EkGMmH8tpCwU2mamgbaNfxcPKqsMTcXG3aQz1KAuuLzmqgGMO49FRV7p/H3Z0EcTYobiz7KITe8LKxtBTPtsFsLGZh507YJ7P2B/O44eBF7eH60J1k+EFZN4vdP3Cn9PH8958DAOCFSzLzYQVjASYVBTRwmAnyiOsv7HW/6SFgz18rluMkZ7igU07CxsiZ5jwRJBIu+JRQNkIAACnutrnH8wK5U69Gulq5DppLbVa/mG7j5fjCXTp/dIVbIWkvlPDPCoktc+r1ImfsQHYm45t4sTFVMm93CIdqYWUo=
  bucket: smart-deploy-artefacts
  upload-dir: "$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER"
  local-dir: "target/universal/"
  skip_cleanup: true

notifications:
  email:
  - allixender@googlemail.com
  webhooks:
    urls:
    - http://admin.smart-project.info/travis/notification
    on_success: always
    on_failure: never
    on_start: never

