apiVersion: v1
kind: Service
metadata:
  annotations:
    notes: "smartportal play http endpoint, proxied via HTTP from NGinx Central"
  labels:
    app: smartportal
    environment: development
  name: smartportal-dev
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: smartportal
    environment: development
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    software: "Play Framework 2.5.6"
    notes: "uses postgres db"
  labels:
    app: smartportal
    environment: development
  name: smartportal-dev
  namespace: default
spec:
  replicas: 1
  selector:
    app: smartportal
    environment: development
  template:
    metadata:
      annotations:
        software: "Play Framework 2.5.6"
        notes: "uses postgres db"
      labels:
        app: smartportal
        environment: development
    spec:
      containers:
      - image: eu.gcr.io/dynamic-cove-129211/smart-portal-backend:76
        imagePullPolicy: IfNotPresent
        name: smartportal-dev
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 398Mi
          requests:
            cpu: 100m
            memory: 192Mi
        env:
        - name: JAVA_OPTS
          value: -Xmx398M
        - name: APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              key: appsecret
              name: play-crypto
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              key: sendgridapikey
              name: sendgridapikey
        - name: GOOGLE_CLIENT_SECRET
          value: "/etc/secrets/client_secret.json"
        - name: PYCSW_URL
          value: "http://pycsw:8080/"
        - name: CSWI_URL
          value: "http://cswingester-dev:9000/"
        - name: UPLOAD_DATA_DIR
          value: "/mnt/data"
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: smartdb1pw
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: smartdb1pw
        - name: PG_DBNAME
          value: jdbc:postgresql://postgres/smartportal_dev
        volumeMounts:
        - mountPath: /mnt/data
          name: upload-cache-vol
        - name: client-json
          mountPath: "/etc/secrets"
          readOnly: true
      restartPolicy: Always
      volumes:
        - name: upload-cache-vol
          emptyDir: {}
        - name: client-json
          secret:
            secretName: google-client-secret
          # gcePersistentDisk:
          #   pdName: upload-cache-vol
          #   fsType: ext4
