apiVersion: v1
kind: Service
metadata:
  annotations:
    notes: "smartportal play http endpoint, proxied via HTTP from NGinx Central"
  labels:
    app: smartportal
    environment: development
  name: smartportal-dev
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: smartportal
    environment: development
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    software: "Play Framework 2.5.6"
    notes: "uses postgres db"
  labels:
    app: smartportal
    environment: development
  name: smartportal-dev
  namespace: default
spec:
  replicas: 1
  selector:
    app: smartportal
    environment: development
  template:
    metadata:
      annotations:
        software: "Play Framework 2.5.6"
        notes: "uses postgres db"
      labels:
        app: smartportal
        environment: development
    spec:
      containers:
      - image: eu.gcr.io/dynamic-cove-129211/smart-portal-backend:0.1
        imagePullPolicy: Always
        name: smartportal-dev
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 398Mi
          requests:
            cpu: 100m
            memory: 192Mi
        env:
        - name: JAVA_OPTS
          value: -Xmx398M
        - name: APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              key: appsecret
              name: play-crypto
      restartPolicy: Always
